import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { MainComponent } from './main/main.component';
import { ArrayBracketSpacingComponent } from './rules/array-bracket-spacing/array-bracket-spacing.component';
import { ArrayCallbackReturnComponent } from './rules/array-callback-return/array-callback-return.component';
import { BanTypesComponent } from './rules/ban-types/ban-types.component';
import { CamelcaseComponent } from './rules/camelcase/camelcase.component';
import { CommaDangleComponent } from './rules/comma-dangle/comma-dangle.component';
import { ComponentClassSuffixComponent } from './rules/component-class-suffix/component-class-suffix.component';
import { ComponentSelectorComponent } from './rules/component-selector/component-selector.component';
import { CurlyComponent } from './rules/curly/curly.component';
import { DefaultCaseComponent } from './rules/default-case/default-case.component';
import { DirectiveClassSuffixComponent } from './rules/directive-class-suffix/directive-class-suffix.component';
import { DirectiveSelectorComponent } from './rules/directive-selector/directive-selector.component';
import { EqeqeqComponent } from './rules/eqeqeq/eqeqeq.component';
import { ExplicitFunctionReturnTypeComponent } from './rules/explicit-function-return-type/explicit-function-return-type.component';
import { GetterReturnComponent } from './rules/getter-return/getter-return.component';
import { IndentComponent } from './rules/indent/indent.component';
import { MaxLenComponent } from './rules/max-len/max-len.component';
import { MaxLinesComponent } from './rules/max-lines/max-lines.component';
import { MaxLinesPerFunctionComponent } from './rules/max-lines-per-function/max-lines-per-function.component';
import { MaxStatementsComponent } from './rules/max-statements/max-statements.component';
import { NoAlertComponent } from './rules/no-alert/no-alert.component';
import { NoBitwiseComponent } from './rules/no-bitwise/no-bitwise.component';
import { NoCompareNegZeroComponent } from './rules/no-compare-neg-zero/no-compare-neg-zero.component';
import { NoConflictingLifecycleComponent } from './rules/no-conflicting-lifecycle/no-conflicting-lifecycle.component';
import { NoConsoleComponent } from './rules/no-console/no-console.component';
import { NoDebuggerComponent } from './rules/no-debugger/no-debugger.component';
import { NoDupeArgsComponent } from './rules/no-dupe-args/no-dupe-args.component';
import { NoDupeKeysComponent } from './rules/no-dupe-keys/no-dupe-keys.component';
import { NoEmptyComponent } from './rules/no-empty/no-empty.component';
import { NoEmptyFunctionComponent } from './rules/no-empty-function/no-empty-function.component';
import { NoEmptyLifecycleMethodComponent } from './rules/no-empty-lifecycle-method/no-empty-lifecycle-method.component';
import { NoEvalComponent } from './rules/no-eval/no-eval.component';
import { NoExtraSemiComponent } from './rules/no-extra-semi/no-extra-semi.component';
import { NoIrregularWhitespaceComponent } from './rules/no-irregular-whitespace/no-irregular-whitespace.component';
import { NoLonelyIfComponent } from './rules/no-lonely-if/no-lonely-if.component';
import { NoMultiSpacesComponent } from './rules/no-multi-spaces/no-multi-spaces.component';
import { NoMultipleEmptyLinesComponent } from './rules/no-multiple-empty-lines/no-multiple-empty-lines.component';
import { NoRestrictedImportsComponent } from './rules/no-restricted-imports/no-restricted-imports.component';
import { NoThrowLiteralComponent } from './rules/no-throw-literal/no-throw-literal.component';
import { NoTrailingSpacesComponent } from './rules/no-trailing-spaces/no-trailing-spaces.component';
import { NoUnreachableComponent } from './rules/no-unreachable/no-unreachable.component';
import { NoUnusedExpressionsComponent } from './rules/no-unused-expressions/no-unused-expressions.component';
import { NoWhitespaceBeforePropertyComponent } from './rules/no-whitespace-before-property/no-whitespace-before-property.component';
import { ObjectCurlySpacingComponent } from './rules/object-curly-spacing/object-curly-spacing.component';
import { PreferConstComponent } from './rules/prefer-const/prefer-const.component';
import { QuotesComponent } from './rules/quotes/quotes.component';
import { RadixComponent } from './rules/radix/radix.component';
import { RequireJsdocComponent } from './rules/require-jsdoc/require-jsdoc.component';
import { SemiComponent } from './rules/semi/semi.component';
import { UseLifecycleInterfaceComponent } from './rules/use-lifecycle-interface/use-lifecycle-interface.component';
import { UsePipeTransformInterfaceComponent } from './rules/use-pipe-transform-interface/use-pipe-transform-interface.component';
import { DefaultCaseLastComponent } from './rules/default-case-last/default-case-last.component';
import { DotNotationComponent } from './rules/dot-notation/dot-notation.component';
import { NoConstAssignComponent } from './rules/no-const-assign/no-const-assign.component';
import { NoDupeClassMembersComponent } from './rules/no-dupe-class-members/no-dupe-class-members.component';
import { NoDupeElseIfComponent } from './rules/no-dupe-else-if/no-dupe-else-if.component';
import { NoDuplicateCaseComponent } from './rules/no-duplicate-case/no-duplicate-case.component';
import { NoDuplicateImportsComponent } from './rules/no-duplicate-imports/no-duplicate-imports.component';
import { NoSelfAssignComponent } from './rules/no-self-assign/no-self-assign.component';
import { NoSelfCompareComponent } from './rules/no-self-compare/no-self-compare.component';
import { NoSetterReturnComponent } from './rules/no-setter-return/no-setter-return.component';
import { NoSparseArraysComponent } from './rules/no-sparse-arrays/no-sparse-arrays.component';
import { NoTemplateCurlyInStringComponent } from './rules/no-template-curly-in-string/no-template-curly-in-string.component';
import { NoUnreachableLoopComponent } from './rules/no-unreachable-loop/no-unreachable-loop.component';
import { NoUnsafeOptionalChainingComponent } from './rules/no-unsafe-optional-chaining/no-unsafe-optional-chaining.component';
import { NoUseBeforeDefineComponent } from './rules/no-use-before-define/no-use-before-define.component';
import { NoUnusedVarsComponent } from './rules/no-unused-vars/no-unused-vars.component';
import { UseIsnanComponent } from './rules/use-isnan/use-isnan.component';
import { ValidTypeofComponent } from './rules/valid-typeof/valid-typeof.component';

const routes: Routes = [
  { path: '', component: MainComponent },
  { path: 'array-bracket-spacing', component: ArrayBracketSpacingComponent },
  { path: 'array-callback-return', component: ArrayCallbackReturnComponent },
  { path: 'ban-types', component: BanTypesComponent },
  { path: 'camelcase', component: CamelcaseComponent },
  { path: 'comma-dangle', component: CommaDangleComponent },
  { path: 'component-class-suffix', component: ComponentClassSuffixComponent },
  { path: 'component-selector', component: ComponentSelectorComponent },
  { path: 'curly', component: CurlyComponent },
  { path: 'default-case', component: DefaultCaseComponent },
  { path: 'default-case-last', component: DefaultCaseLastComponent },
  { path: 'directive-class-suffix', component: DirectiveClassSuffixComponent },
  { path: 'directive-selector', component: DirectiveSelectorComponent },
  { path: 'dot-notation', component: DotNotationComponent },
  { path: 'eqeqeq', component: EqeqeqComponent },
  { path: 'explicit-function-return-type', component: ExplicitFunctionReturnTypeComponent },
  { path: 'getter-return', component: GetterReturnComponent },
  { path: 'indent', component: IndentComponent },
  { path: 'max-len', component: MaxLenComponent },
  { path: 'max-lines', component: MaxLinesComponent },
  { path: 'max-lines-per-function', component: MaxLinesPerFunctionComponent },
  { path: 'max-statements', component: MaxStatementsComponent },
  { path: 'no-alert', component: NoAlertComponent },
  { path: 'no-bitwise', component: NoBitwiseComponent },
  { path: 'no-compare-neg-zero', component: NoCompareNegZeroComponent },
  { path: 'no-conflicting-lifecycle', component: NoConflictingLifecycleComponent },
  { path: 'no-console', component: NoConsoleComponent },
  { path: 'no-const-assign', component: NoConstAssignComponent },
  { path: 'no-debugger', component: NoDebuggerComponent },
  { path: 'no-dupe-args', component: NoDupeArgsComponent },
  { path: 'no-dupe-class-members', component: NoDupeClassMembersComponent },
  { path: 'no-dupe-else-if', component: NoDupeElseIfComponent },
  { path: 'no-dupe-keys', component: NoDupeKeysComponent },
  { path: 'no-duplicate-case', component: NoDuplicateCaseComponent },
  { path: 'no-duplicate-imports', component: NoDuplicateImportsComponent },
  { path: 'no-empty', component: NoEmptyComponent },
  { path: 'no-empty-function', component: NoEmptyFunctionComponent },
  { path: 'no-empty-lifecycle-method', component: NoEmptyLifecycleMethodComponent },
  { path: 'no-eval', component: NoEvalComponent },
  { path: 'no-extra-semi', component: NoExtraSemiComponent },
  { path: 'no-irregular-whitespace', component: NoIrregularWhitespaceComponent },
  { path: 'no-lonely-if', component: NoLonelyIfComponent },
  { path: 'no-multi-spaces', component: NoMultiSpacesComponent },
  { path: 'no-multiple-empty-lines', component: NoMultipleEmptyLinesComponent },
  { path: 'no-restricted-imports', component: NoRestrictedImportsComponent },
  { path: 'no-self-assign', component: NoSelfAssignComponent },
  { path: 'no-self-compare', component: NoSelfCompareComponent },
  { path: 'no-setter-return', component: NoSetterReturnComponent },
  { path: 'no-sparse-arrays', component: NoSparseArraysComponent },
  { path: 'no-template-curly-in-string', component: NoTemplateCurlyInStringComponent },
  { path: 'no-throw-literal', component: NoThrowLiteralComponent },
  { path: 'no-trailing-spaces', component: NoTrailingSpacesComponent },
  { path: 'no-unreachable', component: NoUnreachableComponent },
  { path: 'no-unreachable-loop', component: NoUnreachableLoopComponent },
  { path: 'no-unused-expressions', component: NoUnusedExpressionsComponent },
  { path: 'no-unsafe-optional-chaining', component: NoUnsafeOptionalChainingComponent },
  { path: 'no-use-before-define', component: NoUseBeforeDefineComponent },
  { path: 'no-unused-vars', component: NoUnusedVarsComponent },
  { path: 'no-whitespace-before-property', component: NoWhitespaceBeforePropertyComponent },
  { path: 'object-curly-spacing', component: ObjectCurlySpacingComponent },
  { path: 'prefer-const', component: PreferConstComponent },
  { path: 'quotes', component: QuotesComponent },
  { path: 'radix', component: RadixComponent },
  { path: 'require-jsdoc', component: RequireJsdocComponent },
  { path: 'semi', component: SemiComponent },
  { path: 'use-isnan', component: UseIsnanComponent },
  { path: 'use-lifecycle-interface', component: UseLifecycleInterfaceComponent },
  { path: 'use-pipe-transform-interface', component: UsePipeTransformInterfaceComponent },
  { path: 'valid-typeof', component: ValidTypeofComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
